FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL=/api
ENV VITE_API_URL=${VITE_API_URL}

RUN npm run build


FROM nginxinc/nginx-unprivileged:1.27-alpine

USER root

ARG APP_HOST
COPY nginx.conf /tmp/default.conf.template
RUN test -n "${APP_HOST}" \
    && envsubst '${APP_HOST}' \
        < /tmp/default.conf.template \
        > /etc/nginx/conf.d/default.conf \
    && rm /tmp/default.conf.template

COPY --from=builder /app/dist /usr/share/nginx/html

USER 101

EXPOSE 8080
