"""add live dashboard data

Revision ID: 20260921_live_dashboard
Revises: 6e145355254a
Create Date: 2026-09-21 17:02:28.242674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260921_live_dashboard'
down_revision: Union[str, Sequence[str], None] = '6e145355254a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('nba_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_abbr', sa.String(length=5), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'nba_id', name='uq_player_game_stats_game_player')
    )
    op.create_index(op.f('ix_player_game_stats_game_id'), 'player_game_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_nba_id'), 'player_game_stats', ['nba_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_team_abbr'), 'player_game_stats', ['team_abbr'], unique=False)
    op.add_column('games', sa.Column('status', sa.String(length=12), server_default='scheduled', nullable=False))
    op.add_column('games', sa.Column('status_text', sa.String(length=50), server_default='', nullable=False))
    op.add_column('games', sa.Column('period', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('clock', sa.String(length=30), nullable=True))
    op.execute("UPDATE games SET status = 'final' WHERE score1 IS NOT NULL")
    op.execute("UPDATE games SET status_text = time")
    op.add_column('teams', sa.Column('conference', sa.String(length=4), nullable=True))
    op.add_column('teams', sa.Column('conference_rank', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('last_ten', sa.String(length=10), nullable=True))
    op.add_column('teams', sa.Column('streak', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'streak')
    op.drop_column('teams', 'last_ten')
    op.drop_column('teams', 'conference_rank')
    op.drop_column('teams', 'conference')
    op.drop_column('games', 'clock')
    op.drop_column('games', 'period')
    op.drop_column('games', 'status_text')
    op.drop_column('games', 'status')
    op.drop_index(op.f('ix_player_game_stats_team_abbr'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_nba_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_game_id'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    # ### end Alembic commands ###
