"""update models

Revision ID: 47982c0a622f
Revises: f9a73d4adc47
Create Date: 2026-05-12 13:38:19.446283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47982c0a622f'
down_revision: Union[str, Sequence[str], None] = 'f9a73d4adc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('games', 'time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('teams', sa.Column('nba_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'nba_id')
    op.alter_column('games', 'time',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('games', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
