"""remove team colors

Revision ID: 6e145355254a
Revises: b7f1c2a93e04
Create Date: 2026-05-28 00:33:03.465885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e145355254a'
down_revision: Union[str, Sequence[str], None] = 'b7f1c2a93e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'color')
    op.drop_column('teams', 'accent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('accent', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('color', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
