"""add team_stats

Revision ID: 763d27e46f90
Revises: 5ecad91cab91
Create Date: 2026-05-12 13:56:24.697566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763d27e46f90'
down_revision: Union[str, Sequence[str], None] = '5ecad91cab91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_stats',
    sa.Column('team_abbr', sa.String(length=5), nullable=False),
    sa.Column('form', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('last_scores', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('team_abbr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_stats')
    # ### end Alembic commands ###
