"""add_foreign_key_relationships

Revision ID: e783596e4ef2
Revises: deb006c78fda
Create Date: 2026-05-20 13:41:54.670410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e783596e4ef2'
down_revision: Union[str, Sequence[str], None] = 'deb006c78fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'team1',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('games', 'team2',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('games', 'season_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'regular'::character varying"))
    op.create_foreign_key(None, 'games', 'teams', ['team1'], ['abbr'], ondelete='SET NULL')
    op.create_foreign_key(None, 'games', 'teams', ['team2'], ['abbr'], ondelete='SET NULL')
    op.create_foreign_key(None, 'injuries', 'teams', ['team_abbr'], ['abbr'])
    op.alter_column('players', 'nba_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'players', 'teams', ['team_abbr'], ['abbr'])
    op.create_foreign_key(None, 'team_stats', 'teams', ['team_abbr'], ['abbr'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_stats', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.alter_column('players', 'nba_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'injuries', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.alter_column('games', 'season_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'regular'::character varying"))
    op.alter_column('games', 'team2',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('games', 'team1',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###
