"""init

Revision ID: f9a73d4adc47
Revises: 
Create Date: 2026-05-08 15:50:49.280268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a73d4adc47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('team1', sa.String(length=5), nullable=False),
    sa.Column('team2', sa.String(length=5), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=False),
    sa.Column('is_today', sa.Boolean(), nullable=False),
    sa.Column('win1', sa.Float(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_abbr', sa.String(length=5), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=15), nullable=False),
    sa.Column('injury', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('abbr', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('accent', sa.String(length=10), nullable=False),
    sa.Column('record', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('abbr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('injuries')
    op.drop_table('games')
    # ### end Alembic commands ###
